sudo: required


services:
  - docker
before_install:
  - docker build -t chaqattack/devops-files-app ./devops-test-app-files

script:
  - docker run chaqattack/devops-files-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DevOps FilesApp"
  env: "DevopsFilesapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-911266112348"
  bucket_path: "DevOps FilesApp"
  on:
    branch: "master"
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  
