sudo: required
services: 
  - docker

before_install:
  - docker build -t chaqattack/devops-files-app --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY --build-arg AWS_SECRET_KEY=$AWS_SECRET_KEY ./devops-test-app-files
  - docker build -t chaqattack/devops-users-app --build-arg DB_USERNAME=$DB_USERNAME  --build-arg DB_PASSWORD=$DB_PASSWORD ./devops-test-app-users

script:
    - docker run -e CI=true chaqattack/devops-files-app npm run test
    - docker run -e CI=true chaqattack/devops-users-app npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DevOps-TestApp"
  env: "DevopsTestapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-911266112348"
  bucket_path: "DevOps-TestApp"
  on:
    branch: "master"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"