sudo: required
services: 
  - docker

before_install:
  - docker build -t devops-files-app --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_USER_BUCKET_NAME=$AWS_USER_BUCKET_NAME --build-arg AWS_REGION=$AWS_REGION --build-arg ENV=$ENV ./devops-test-app-files
  - docker build -t devops-users-app --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_NAME=$DB_NAME --build-arg DB_HOST=$DB_HOST --build-arg DB_ENV=$DB_ENV ./devops-test-app-users

script:
  - docker run -e CI=true devops-users-app npm run test
  
after_success:  
  
  #- docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PSW
  
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin 
  - eval $(aws ecr get-login --region us-east-2 | sed s'/\-e\ none//'g)
  # TAGGIN IMAGES
  #- docker tag chaqattack/devops-users-app:latest chaqattack/devops-users-app
  #- docker tag chaqattack/devops-files-app:latest chaqattack/devops-files-app
  
  #TAGGING LATEST
  - docker tag devops-files-app:latest 911266112348.dkr.ecr.us-east-2.amazonaws.com/files-app:latest
  - docker tag devops-users-app:latest 911266112348.dkr.ecr.us-east-2.amazonaws.com/user-app:latest
  - docker push 911266112348.dkr.ecr.us-east-2.amazonaws.com/files-app:latest
  - docker push 911266112348.dkr.ecr.us-east-2.amazonaws.com/users-app:latest

  #TAGGIN BUILD NUMBER
  - docker tag devops-files-app 911266112348.dkr.ecr.us-east-2.amazonaws.com/files-app:$TRAVIS_BUILD_NUMBER
  - docker tag devops-users-app 911266112348.dkr.ecr.us-east-2.amazonaws.com/users-app:$TRAVIS_BUILD_NUMBER
  - docker push 911266112348.dkr.ecr.us-east-2.amazonaws.com/files-app:$TRAVIS_BUILD_NUMBER
  - docker push 911266112348.dkr.ecr.us-east-2.amazonaws.com/users-app:$TRAVIS_BUILD_NUMBER
  
  # PUSHING IMAGES
  ## PUSHING LATEST
 
  #- docker push chaqattack/devops-files-app
  #- docker push chaqattack/devops-users-app

  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DevOps-TestApp"
  env: "DevopsTestapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-911266112348"
  bucket_path: "DevOps-TestApp"
  on:
    branch: "master"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"