sudo: required
services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DevOps FilesApp"
  env: "DevopsFilesapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-911266112348"
  bucket_path: "DevOps FilesApp"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_accessKey:
    secure: "$AWS_SECRET_KEY"

  
