sudo: required
services: 
  - docker

before_install:
  - docker build -t chaqattack/devops-files-app --build-arg AWS_ACCESS_KEY=$AWS_ACCESS_KEY --build-arg AWS_SECRET_KEY=$AWS_SECRET_KEY --build-arg AWS_USER_BUCKET_NAME=$AWS_USER_BUCKET_NAME --build-arg AWS_REGION=$AWS_REGION --build-arg ENV=$ENV ./devops-test-app-files
  - docker build -t chaqattack/devops-users-app --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg DB_NAME=$DB_NAME --build-arg DB_HOST=$DB_HOST --build-arg DB_ENV=$DB_ENV ./devops-test-app-users

script:
  - docker run -e CI=true chaqattack/devops-users-app npm run test
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PSW
  - docker tag chaqattack/devops-files-app:latest chaqattack/devops-files-app
  - docker push chaqattack/devops-files-app
  - docker tag chaqattack/devops-users-app:latest chaqattack/devops-users-app
  - docker push chaqattack/devops-users-app

  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DevOps-TestApp"
  env: "DevopsTestapp-cantigua"
  bucket_name: "elasticbeanstalk-us-east-2-911266112348"
  bucket_path: "DevOps-TestApp"
  on:
    branch: "master"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"