version: '3'
services:
  devops-global-postgres:
    image: "postgres:9.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "devops_test"

  webapp:
    build: .
    image: webapp
    depends_on:
      - devops-global-postgres
    environment:
      DEVOPS_TEST_PORT: "3091"
      DEVOPS_TEST_ENV: "development" 
    command: ["./wait.sh", "devops-global-postgres:5432"] 
    command: ["npm", "run", "migrate-up"] 
    command: ["npm", "run", "start"]   
    